version: "3.0"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - POSTGRES_DSN=postgres://sbdoddi:password@postgres:5432/innoscripta?sslmode=disable

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sbdoddi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: innoscripta
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres-data:
